on: [push, pull_request]

name: Conformance Suite

jobs:
  conformance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: build
          args: --manifest-path=tests/conformance/Cargo.toml
      - uses: sigstore/sigstore-conformance@main
        with:
          entrypoint: ${{ github.workspace }}/tests/conformance/target/debug/sigstore